### ISSUE TITLE
opening the gui when blocks.json is empty causes a game crash

### ISSUE THREAD

**Issue by im-ener** [AdvancedXRay/XRay-Fabric#100]
**Describe the bug**
opening the gui when blocks.json is empty causes a game crash

**To Reproduce**
1. delete everything in blocks.json (my computer is very weird and does this when i restart my computer for some reason)
2. open the block gui (the game will crash basically immediately)

**Expected behavior**
empty xray block list

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: 1.21
 - XRay Mod Version: 21.0/0

**Comment by MichaelHillcox** [comment]
Crashlog please
