### ISSUE TITLE
IT DOES NOT WORK!!!!

### ISSUE THREAD

**Issue by BuckManglitz01** [AdvancedXRay/XRay-Fabric#101]
So I like this mod and I just lost my shulker box. but this mod no longer works, the second I load the world, it kicks me and says 

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "pro.mikey.fabric.xray.StateSettings.isActive()" because the return value of "pro.mikey.fabric.xray.storage.SettingsStore.get()" is null

---- Minecraft Crash Report ----
// You're mean.

Time: 2024-08-10 09:44:54
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "pro.mikey.fabric.xray.StateSettings.isActive()" because the return value of "pro.mikey.fabric.xray.storage.SettingsStore.get()" is null
	at pro.mikey.fabric.xray.screens.forge.GuiOverlay.RenderGameOverlayEvent(GuiOverlay.java:19)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:28)
	at net.minecraft.class_329.handler$znp000$fabric-rendering-v1$render(class_329.java:1538)
	at net.minecraft.class_329.method_1753(class_329.java:220)
	at net.minecraft.class_757.method_3192(class_757.java:896)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pro.mikey.fabric.xray.screens.forge.GuiOverlay.RenderGameOverlayEvent(GuiOverlay.java:19)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:28)
	at net.minecraft.class_329.handler$znp000$fabric-rendering-v1$render(class_329.java:1538)
	at net.minecraft.class_329.method_1753(class_329.java:220)

-- Uptime --
Details:
	JVM uptime: 155.437s
	Wall uptime: 101.785s
	High-res time: 93.553s
	Client ticks: 1254 ticks / 62.700s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Buck_Manglitz_01'/67, l='ClientLevel', x=-1876.96, y=-50.08, z=2854.89]]
	Chunk stats: 256, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (131,69,234), Section: (at 3,5,10 in 8,4,14; chunk contains blocks 128,-64,224 to 143,319,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 27672593 game time, 2330505 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 1

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, advanced-xray-fabric, biomeinfo, boatfly, caffeineconfig, cloth-config, crafting-enchanted-golden-apple-fabric, distanthorizons, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, freecam, indium, infinite-night-vision, libertyvillagers, logical_zoom, modernfix, modmenu, murgers, nolancheating, old_combat_mod, rideable-llamas, sereneseasons, sodium, sodium-extra, stackable, villager-pickup, file/C4Music_v3.2.zip, file/Better Clear Water 1.19.zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 373113944 bytes (355 MiB) / 838860800 bytes (800 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4600
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 10.18.15.4248
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MiB): 20203.16
	Virtual memory used (MiB): 7487.34
	Swap memory total (MiB): 12088.14
	Swap memory used (MiB): 508.81
	Space in storage for jna.tmpdir (MiB): available: 621978.44, total: 713990.69
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 621978.44, total: 713990.69
	Space in storage for io.netty.native.workdir (MiB): available: 621978.44, total: 713990.69
	Space in storage for java.io.tmpdir (MiB): available: 621978.44, total: 713990.69
	Space in storage for workdir (MiB): available: 621978.44, total: 713990.69
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 21.0.0
		ante: Anvil Never Too Expensive 1.2
		biomeinfo: BiomeInfo 1.21-18
		boatfly: Boat Fly 5.0.0
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.80
		crafting-enchanted-golden-apple-fabric: Crafting Enchanted Golden Apple Fabric 1.0.3
		distanthorizons: Distant Horizons 2.1.2-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.9+98a7dbbb90
			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+686dcdce90
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d132107690
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.3+b559734490
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		fabric-api: Fabric API 0.100.1+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.65+b559734490
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b9990
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a790
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a790
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.11+b559734490
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.12+7f945d5b90
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.2.1+d153f34490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a790
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.22+6a6dfa1990
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.6+16c4ae2590
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9990
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b9990
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8c90
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+00ab0a6390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b390
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.9+6573ed8c90
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c90
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b90
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.10+d132107690
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c90
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.8+6573ed8c90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.21+b9828ba390
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6b90
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.3+cc9f121a90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b559734490
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f34490
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.78+b559734490
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.12+b559734490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8c90
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		freecam: Freecam 1.3.0-beta1+mc1.21
		giantspawn: Giant Spawn 5.2
		glitchcore: GlitchCore 2.0.0.2
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
			net_jodah_typetools: typetools 0.6.3
		indium: Indium 1.0.34+mc1.21
		infinite-night-vision: Infinite Night Vision 1.0.0
		java: OpenJDK 64-Bit Server VM 21
		libertyvillagers: Liberty's Villagers 1.0.15+fabric+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
				packet_tweaker: Packet Tweaker 0.5.1+24w03b
		logical_zoom: Logical Zoom 0.0.25
		minecraft: Minecraft 1.21
		modernfix: ModernFix 5.19.0+mc1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		murgers: Murgers 1.3.0
		nametagtweaks: Name Tag Tweaks 3.6
		nolancheating: No LAN Cheating 1.2
		old_combat_mod: Old Combat Mod 1.1.1
		rideable-llamas: Rideable Llamas Mod 1.0.0
		sereneseasons: SereneSeasons 10.0.0.2
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.6+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		stackable: Stackable 1.2.1
		treeharvester: Tree Harvester 8.9
		villager-pickup: Villager Pickup 1.1.2
		villagerdeathmessages: Villager Death Messages 3.4
		villagernames: Villager Names 7.4
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Intel(R) HD Graphics 4600 GL version 3.2.0 - Build 10.18.15.4248, Intel
	Window size: 854x480
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Render Distance: 2/2 chunks
	Resource Packs: vanilla, fabric, advanced-xray-fabric, biomeinfo, boatfly, caffeineconfig, cloth-config, crafting-enchanted-golden-apple-fabric, distanthorizons (incompatible), fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, freecam, indium, infinite-night-vision, libertyvillagers, logical_zoom, modernfix (incompatible), modmenu, murgers, nolancheating, old_combat_mod, rideable-llamas, sereneseasons (incompatible), sodium, sodium-extra, stackable, villager-pickup, file/C4Music_v3.2.zip (incompatible), file/Better Clear Water 1.19.zip (incompatible)
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 4x Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Buck_Manglitz_01'/67, l='ServerLevel[world]', x=-1876.96, y=-50.00, z=2854.89]]
	Active Data Packs: vanilla, fabric, collective, crafting-enchanted-golden-apple-fabric, fabric-convention-tags-v2, libertyvillagers, murgers, nametagtweaks, sereneseasons (incompatible), server_translations_api
	Available Data Packs: bundle, collective, crafting-enchanted-golden-apple-fabric, fabric, fabric-convention-tags-v2, libertyvillagers, murgers, nametagtweaks, sereneseasons (incompatible), server_translations_api, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -2744409246155750876

**Comment by MichaelHillcox** [comment]
Sounds like something is borked. Try deleting the config file and see if that fixes it

**Comment by BuckManglitz01** [comment]
where is the location
