### ISSUE TITLE
seed xray

### ISSUE THREAD

**Issue by Stove-git** [AdvancedXRay/XRay-Fabric#103]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
seed xray

**Describe alternatives you've considered**
none were considered

**Comment by MichaelHillcox** [comment]
Unless you know how to do this, I have absolutely no plans on doing this

**Comment by Stove-git** [comment]
i can try researching

**Comment by Stove-git** [comment]
> Unless you know how to do this, I have absolutely no plans on doing this
this function is in meteor mod with meteor reject plugin for the mod(mod)
also it is in aristois called seedray
