### ISSUE TITLE
1.21 for forge?

### ISSUE THREAD

**Issue by raccoonzez** [AdvancedXRay/XRay-Fabric#105]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I was just wondering if the mod is gonna be updated to the latest version of Minecraft, its one of the best xray mods out there

**Comment by MichaelHillcox** [comment]
Fixed, just tagged the CF release as 1.21.1 supported. The mod is already on 1.21 :D

**Comment by raccoonzez** [comment]
i appreciate that, though is it only getting updated for neoforge or is there gonna be a 1.21-1.21.1 for regular Forge?

**Comment by MichaelHillcox** [comment]
Unlikely to get a forge version.

**Comment by raccoonzez** [comment]
what if I said pretty please with a cherry on top

**Comment by MichaelHillcox** [comment]
Oh, I thought this was a different mod. X-ray for forge is already out for 1.21.1

**Comment by raccoonzez** [comment]
i only see it out for neoforge

**Comment by raccoonzez** [comment]
im realizing i posted this in the fabric section, thats my bad
