### ISSUE TITLE
Xray mod crash due to "pro.mikey.fabric.xray.storage.BlockStore.get()" is null

### ISSUE THREAD

**Issue by WeekCraft** [AdvancedXRay/XRay-Fabric#106]
**Describe the bug**
Game will crash when attempting to open GUI

**To Reproduce**
Press set Key to open Xray GUI

**Expected behavior**
Game will crash upon trying to Open GUI

Additionally The Xray outlines will not be able render
![image_2024-09-12_205652013](https://github.com/user-attachments/assets/5c8bbd98-bf3d-46dd-8795-12d10b690611)

 - Minecraft Version: 1.21
 - XRay Mod Version: 21.0.0
 
 Crash report blow
 .[crash-2024-09-12_19.54.26-client.txt](https://github.com/user-attachments/files/16984775/crash-2024-09-12_19.54.26-client.txt)

**Comment by eyebrawl123** [comment]
have the same problem

Minecraft Version: 1.21
XRay Mod Version: 21.0.0

**Comment by MichaelHillcox** [comment]
See solution here https://github.com/AdvancedXRay/XRay-Fabric/issues/84#issuecomment-2412247650
