### ISSUE TITLE
Error in version 1.21.3

### ISSUE THREAD

**Issue by KaitoWolf29** [AdvancedXRay/XRay-Fabric#108]
Hi, every time I try to open the GUI, the game crashes. This is strange because in previous versions, like 1.21.1 and 1.21.2, I didn’t have any issues. I already have the updated versions of Fabric and its API to ensure compatibility.

I've attached a screenshot of the error message.

I hope you can help me, please.

![Captura de pantalla 2024-10-29 200129](https://github.com/user-attachments/assets/0c3561b1-dd46-4ede-a5ef-10f872157d23)

**Comment by MichaelHillcox** [comment]
The mod is not ported yet.
