### ISSUE TITLE
modded ores in list turn to minecraft:air after game restart

### ISSUE THREAD

**Issue by DougStoker** [AdvancedXRay/XRay-Fabric#21]
**Describe the bug**
modded ores in list turn to minecraft:air after game restart

**To Reproduce**
1. add a mod ore to the list
2. exit and re launch the game

**Expected behavior**
the block list stays like i put it

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.12.2]
 - 1.17
 - XRay Mod Version: [eg: 1.5.0]
 - 0.6.0-build.8
 - Mod Pack & Version if applicable
 - every fabric 1.17 modpack i've played
 - Forge Version if applicable

**Additional context**
Add any other context about the problem here
![Screen Shot 2021-10-18 at 11 22 52 PM](https://user-images.githubusercontent.com/40470811/137848640-f6f4ae7b-b884-46af-988a-c05fbfda338e.png)
![Screen Shot 2021-10-18 at 11 22 01 PM](https://user-images.githubusercontent.com/40470811/137848646-4fe595ec-e4d1-4f90-b516-0982cca6ab5f.png)
.

**Comment by zai205** [comment]
yeah I'm having the same problem haven't found a way around it

**Comment by MichaelHillcox** [comment]
IIRC, This has been resolved, please let me know if this is still an issue
