### ISSUE TITLE
Ore outlines don't appear

### ISSUE THREAD

**Issue by Memer56** [AdvancedXRay/XRay-Fabric#28]
**Describe the bug**
When x-ray is active no matter what block is supposed to have an outline, the outline won't appear.

**To Reproduce**
Steps to reproduce the behaviour:
Playing in minecraft version 1.18

**Expected behaviour**
When pressing G the outlines for the ores I want to see should appear.

**Minecraft Environment**
 - Minecraft Version: 1.18
 - XRay Mod Version: advanced-xray-fabric-1.18-0.7.0-build.10.jar
 - Forge Version: 0.12.8

**Comment by MichaelHillcox** [comment]
Most likely, you've not configured blocks, or you're using shaders.
