### ISSUE TITLE
Modded Blocks do not persist in the Xray list

### ISSUE THREAD

**Issue by Pale-Champion-Atom596** [AdvancedXRay/XRay-Fabric#32]
When there are modded blocks in the list of xray blocks, they do not save. After leaving and rejoining the world, the blocks no longer appear with wireframes when using xray. In the list of blocks, they don't show models, and must be deleted from the list and readded.

1. Install a mod that adds new blocks
2. Add the new modded block to the xray list
3. Leave the world and exit to menu
4. Reenter the world and the block will not render in xray anymore

Modded blocks should work just like how vanilla blocks do.

 - Minecraft Version: 1.18.1
 - XRay Mod Version: 0.7.0 build 10

**Comment by MichaelHillcox** [comment]
Fixed as of 1.19 and back ported to 1.18.2
