### ISSUE TITLE
HUD overlapping

### ISSUE THREAD

**Issue by Phoupraw** [AdvancedXRay/XRay-Fabric#37]
**Is your feature request related to a problem? Please describe.**
When xray enabled, there is a text at the up left of screen. It overlaps with other hud, such as F3 and minihud.
![image](https://user-images.githubusercontent.com/50520903/180640449-6d96d78c-89ed-4e3f-953b-909a3673d33e.png)

**Describe the solution you'd like**
A setting to set the position of the text. Or a setting to turn on/off the text.

**Comment by MichaelHillcox** [comment]
Sorted in 1.19.3
