### ISSUE TITLE
sculk shriekers not highlighted

### ISSUE THREAD

**Issue by corgidotcom** [AdvancedXRay/XRay-Fabric#39]
tried turning xray on and off again, because I wasnt sure if it was a render glitch or something, but after doing so plenty of times the sculk sensors just dont get highlighted. i had a red highlight for them so they should be obvious

 - Minecraft Version: [1.19 fabric]
 - XRay Mod Version: [1.1.0 build 12]
![2022-08-10_20 06 17](https://user-images.githubusercontent.com/107601746/184060004-aab95dfc-3fef-43c8-aa67-1c61c3eb5407.png)

**Comment by Crittically** [comment]
I had the same problem but managed to fix it simply by enabling the "Scan for all block states" option. I think it has something to do with there being 2 versions of the shrieker, the naturally generated one and the player placed one, not sure though.

**Comment by MichaelHillcox** [comment]
See the above. This is how you fix it.
