### ISSUE TITLE
X-ray on exposed minerals

### ISSUE THREAD

**Issue by BlueDeer233** [AdvancedXRay/XRay-Fabric#40]
Many paper-forked servers deploy the anti-Xray plugin.
When using this mod on these servers, players cannot distinguish between real minerals.

Can you analyze whether one side of the mineral is exposed to the air and add a button to turn on this feature?

**Comment by randomairborne** [comment]
If you had taken two seconds to read, you’d know that this mod does not support servers at all. 
Good day.

**Comment by BlueDeer233** [comment]
Okay, thank you at all.
