### ISSUE TITLE
crashed report

### ISSUE THREAD

**Issue by L1nk798** [AdvancedXRay/XRay-Fabric#44]
hi since the update will the crash if i enabled xray

need fix :) 
![Download](https://user-images.githubusercontent.com/104328531/192100599-72110307-90d6-48b7-b4ee-31df1b1f9315.png)
[crash-2022-09-24_14.34.34-client.txt](https://github.com/AdvancedXRay/XRay-Fabric/files/9638789/crash-2022-09-24_14.34.34-client.txt)

**Comment by MichaelHillcox** [comment]
Fixed in 1.19.3, if this keeps happening in < 1.19.2, just delete the config in /config/advancedxray/blocks.json
