### ISSUE TITLE
Crashed on Use

### ISSUE THREAD

**Issue by yudhistiraindyka** [AdvancedXRay/XRay-Fabric#45]
**Describe the bug**
Hello, I used to have no problems using this mod. But once I migrated to 1.19.2 it always crashes when I press G to access mod config.

**To Reproduce**
1. Join a Minecraft world
2. Press G to access config
3. Crash

**Expected behavior**
I believe it shouldn't crash and should allow me to config the blocks that should appear when I enable the xray.

**Screenshots**
![2022-09-26_20 40 05](https://user-images.githubusercontent.com/33085123/192292608-fddb5434-38b5-4a95-8b89-8ef6a336d779.png)

**Minecraft Environment**
 - Minecraft Version: Fabric 1.19.2
 - XRay Mod Version: advanced-xray-fabric-1.19-1.1.0-build.12.jar

**Comment by MichaelHillcox** [comment]
Attach the crash log
