### ISSUE TITLE
Update github source 

### ISSUE THREAD

**Issue by anna-s-h** [AdvancedXRay/XRay-Fabric#46]
**Is your feature request related to a problem? Please describe.**
It seems that this github repository does not have the code from the build 1.18.2-1.0.1, and was last updated 2 years ago, and not a few months ago

**Describe the solution you'd like**
An up-to-date repo

**Additional context**
I'm trying to contribute filtering by tag, and might look into making that work with the gui, or groups, or something. But while I can download the source code from releases and edit that, it's a little inconvenient to not be able to just clone the repo.

**Comment by Vort** [comment]
Do it means that this project is actually closed source?

**Comment by MichaelHillcox** [comment]
It's in a different branch...
