### ISSUE TITLE
Request for the option to change the on-screen position of the location-info (and change font size too if possible) (additionally: issue with fps display format)

### ISSUE THREAD

**Issue by VincedPie** [AdvancedXRay/XRay-Fabric#52]
**Is your feature request related to a problem? Please describe.**
i use xaero's minimap and for me that works best in the top left corner. unfortunately the location-info feature of this mod here is also displayed in the top left corner. now, of course xaero's Mm lets me change the position of the map freely and i could just move it down a little so it doesn't overlap with the info-line anymore but I'm just not exactly a huge fan of that. on a similar vaguely related note, I would also enjoy the option to be able to change the font-size of the info-line as, for me personally, like half the text size would be enough.

apart from this, I would also like to point out an issue I have with the format of the fps display format. My Graphics card uses vsync fps stabilizer and when I add the %fps argument to the location-format text field, it not only displays the current fps i get but also additional text saying "fps T: 120 vsyncfancy fancy-clouds B: 2" which looks kinda obstructive overall. (see last screenshot i have attached)

**Describe the solution you'd like**
for the position change, maybe there could be a button with a few fixed positions as choices when you click through the button ( like "top left","top","top right" ect) or perhaps even a config screen like the xaero's minimap mod, that lets me drag the info-line where ever i like it best on the screen.  the latter option would be quite ideal for me because then i could drag it to where the map infos of Xearo's are and it they would complement each other seamlessly :>
For the font size, there could maybe be a slider, that lets the user choose from like 8pt to 36pt or so, or there could be a button with fixed choices like "big", "medium" or "small" for example, where medium could be the current displayed size and small like half of that and big like 1.5 of the current size? 

the fps thing: could you make it so the %fps format only shows the current fps without the additional text? that would be great :)

**Describe alternatives you've considered**
i have tried just adding a few spaces before the location info in the "Format" text-field, so it moves the info further right on the screen, but this only works as long as i don't turn on any of the x-ray/cave-modes bc they still appear at the far left corner and they just move the info-text further to the middle of the screen, which doesn't look good. 
for the font size thing, i tried to find where it could maybe be in the class-files of this mod and change it there manually to my liking, but unfortunately i don't know jack sh*t about coding with java and i wasn't able to find it of even add the feature myself.
putting the map at the other side of the screen also isn't really an option for me bc my stupid little brain is so used to it being on that side and in my mind this minimap just "belongs" there if that makes any sense :0 

**Additional context**
How it looks without repositioning anything:
![2022-12-11_15 32 38](https://user-images.githubusercontent.com/119973581/206912140-ec558b22-8f3a-4491-94ed-92c51bcf0341.png)

Adding spaces to the info-line:
![2022-12-11_16 12 18kopie](https://user-images.githubusercontent.com/119973581/206912612-12147a70-c705-446c-adbe-9106e436df03.png)

but then when i activate one of the modes, this happens :(
![2022-12-11_16 12 42kopie](https://user-images.githubusercontent.com/119973581/206912644-4f5cbbbb-4ef3-40cd-bebd-eacaf93297a2.png)

moving the minimap down, however, I'm not the biggest fan of this bc the line is so tall (smaler font could be a remedy for this):
![2022-12-11_16 14 13kopie](https://user-images.githubusercontent.com/119973581/206912724-a10460a6-95a5-4340-a48e-64a6a82566d2.png)
![2022-12-11_16 14 21kopie](https://user-images.githubusercontent.com/119973581/206912738-1888a18e-9287-4554-9145-fa30bc2d53cc.png)

The Issue with the fps format:
![2022-12-11_16 14 55](https://user-images.githubusercontent.com/119973581/206913111-e6fe82c1-d512-4973-8e8b-92a214898a2b.png)

Huge thanks to your time and effort you put into this. looking forward to your response :)
Have a nice day :>

**Comment by MichaelHillcox** [comment]
Can you tell me what version of my mod you're using?

**Comment by VincedPie** [comment]
> Can you tell me what version of my mod you're using?

ffhagFHSDGj bro I'm so sorry, i just realized i posted this to the wrong xray mod github omg (I feel incredibly stupid rn fffff)
