### ISSUE TITLE
No blocs identified below level 0

### ISSUE THREAD

**Issue by kevinrenard** [AdvancedXRay/XRay-Fabric#57]
**Describe the bug**
When I activate XRay, I am only able to see the blocs that are at level 0 or more

**To Reproduce**
1. go deep at level 0 or below
2. activate XRay

**Expected behavior**
Blocs of minerals should be displayed

**Minecraft Environment**
 - Minecraft Version: 1.19.3
 - XRay Mod Version: advanced-xray-fabric-1.19.3-1.3.0-build.14
 - Fabric Version: 0.14.12

**Comment by okMajd** [comment]
make sure you have deepslate ores toggled in the xray gui

**Comment by MichaelHillcox** [comment]
IIRC, This has been resolved, please let me know if this is still an issue. But yes, also make sure you have deepslate ores enabled as well
