### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by lightumcc** [AdvancedXRay/XRay-Fabric#66]
as the title, thanks

**Comment by MelchiorGaspar** [comment]
I would like to see an update for v1.20.1 too.
please and thanks.

**Comment by MichaelHillcox** [comment]
Omg, people want mods updated? No way? Who would have guessed...

Thank god you've all come here to pester me to update the mods I still actively maintain, whilst also being more than aware the MC has updated...

Yes, I am of course going to be updating my mods.

**Comment by MelchiorGaspar** [comment]
@MichaelHillcox hi
omg sry to bug you, didn't mean to pester you..
thx for still being active.. :D ^_^
