### ISSUE TITLE
Only shows enabled blocks that are exposed

### ISSUE THREAD

**Issue by DreezyMoto** [AdvancedXRay/XRay-Fabric#68]
**Describe the bug**
Doesn't show blocks that are buried and only half the time does it show enabled blocks. have to turn it off and back on multiple times for it to notice blocks im standing next to

**To Reproduce**
1. Use mod as intended

**Expected behavior**
For it to show all blocks im searching for whether its exposed or not

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.20.1]
 - XRay Mod Version: [eg: 1.6.0]

**Comment by MichaelHillcox** [comment]
I've never seen this happen. If you're running other mods this could get in the way. If this is still an issue for you, please let me know with more info
