### ISSUE TITLE
Changing mod Description to avoid.. to another mod

### ISSUE THREAD

**Issue by BeastAsDier** [AdvancedXRay/XRay-Fabric#69]
**Is your feature request related to a problem? Please describe.**
No it not

**Describe the solution you'd like**
...

**Describe alternatives you've considered**
...
**Additional context**
...
**My Request**
So i was wondering that is there anyway to change mod description and it icon so that we can join any server without getting caught? like changing mods description to another mods description.

**Comment by MichaelHillcox** [comment]
No
