### ISSUE TITLE
crashes on Z

### ISSUE THREAD

**Issue by dir3w0lf12** [AdvancedXRay/XRay-Fabric#70]
Xray crashes when I try to activate the GUI

**Steps to reproduce**
Simply press Z on Fabric

**Expected behavior**
Shows GUI

**Minecraft Enviorment**
 - Minecraft Version: 1.19.2
 - XRay Mod Version: 1.3.0

https://mclo.gs/af6HnUu
crash log

**Comment by Fyphen1223** [comment]
Me too, and I have no idea what's going on.

**Comment by MichaelHillcox** [comment]
Wrong mod version for your Minecraft version

**Comment by MichaelHillcox** [comment]
> Me too, and I have no idea what's going on.

Please make a new issue
