### ISSUE TITLE
Toggleable Server Attributes

### ISSUE THREAD

**Issue by ItsCliffGaming** [AdvancedXRay/XRay-Fabric#79]
The link to the Discord is broken, otherwise this is something I would like have went to the Discord server to discuss/suggest:

I have a server with Custom Origins on it, and I would love if this had the ability to use as a server mod, where the client doesn't need it, and where it could be toggled with an attribute or via a command, so I could implement it as an Origins power. 

The idea I have is one of the origins is mining related, and they can use their "activate" ability to see ores through the wall for 30 seconds, with a 5 minute cooldown. Origins can handle all that - but I don't think it can activate/deactivate the ability, and also I wouldn't really want them to have the mod on client side, because then they could bypass the limitations of the power.

**Comment by MichaelHillcox** [comment]
This isn't possible. The mod is required on the client.
