### ISSUE TITLE
Custom Ores from mods do not show on overlay when trying to x-ray them.

### ISSUE THREAD

**Issue by spjoes** [AdvancedXRay/XRay-Fabric#8]
**Describe the bug**
Custom Ores from mods do not show on overlay when trying to x-ray them. Vanilla ores work fine

**To Reproduce**
1. click "g" to open the menu
2. add a custom ore to your list
3. Enable X-Ray

**Expected behavior**
I expected the custom ores to appear on the x-ray overlay like vanilla ores

**Minecraft Enviorment**
 - Minecraft Version: 1.16.5
 - XRay Mod Version: 0.5.0
 - Fabric

**Comment by MichaelHillcox** [comment]
What custom ore? From what mod?

**Comment by spjoes** [comment]
It was an ore from my mod (which is still in development) called Zircon. I am now realizing that maybe this is an issue because i need to add the custom ore block to some sort of tag?

**Comment by MichaelHillcox** [comment]
Unlikely, this sounds like it might be an issue on either of our sides, I don't use tags, I use state checking but it can be anything from very strict to very loose in the way it checks

**Comment by MichaelHillcox** [comment]
Is you mod open source? Could you share the states of your ores? Could you DM me a dev jar at MiKeY@3704
