### ISSUE TITLE
Add a tracer option to all and a Update every tick X option to refresh the xray every few ticks.

### ISSUE THREAD

**Issue by Dormant11** [AdvancedXRay/XRay-Fabric#80]
Add a tracer option to all and a Update every tick X option to refresh the xray every few ticks.

The tracer is to be like other hack clients but works for 1.20.2 which is unlike my client of choice, and the update every tick option is to not have to turn off and on the mod to get a new data set.

**Comment by Dormant11** [comment]
Add a tracer option to all and a Update every tick X option to refresh the xray every few ticks.

The tracer is to be like other hack clients but works for 1.20.2 which is unlike my client of choice, and the update every tick option is to not have to turn off and on the mod to get a new data set.

**Comment by MichaelHillcox** [comment]
This isn't a hacked client and I won't be adding tracers. I also won't be adding updating every X ticks due to the performance issues with that.
