### ISSUE TITLE
max distance of xray is 15

### ISSUE THREAD

**Issue by bombaatomowa123456** [AdvancedXRay/XRay-Fabric#81]
max distance of xray is 15

to reproduce:download the mod and try to put the distnace over 15

Expected behavior:being able to go to 64 or something like that

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.19.2]
 - XRay Mod Version: [eg: 1.1.0]

please help

even worse THE ORES DONT HIGHLIGHTED AT ALL???

**Comment by MichaelHillcox** [comment]
15 is chunks, not blocks
