### ISSUE TITLE
1.20.1 Gui keybind crash/xray doesnt show

### ISSUE THREAD

**Issue by CubixCola** [AdvancedXRay/XRay-Fabric#84]
so im on 1.20.1 version of this only because of some fabric mod restrictions i have, but when toggling the keybind for activating/deactivating xray, it never shows anything? i used this mod literally the day before yesterday and it was completely fine, but now it just doesnt work at all, doesnt highlight blocks or anything. and when you press 'G' to access the GUI, it just crashes the game, always just "Saving World" *crash* I've tried to rebind the key maybe seeing if that does it, but no it doesn't. this similar bug happened sometime for one of the 1.19 versions, where if you would just activate the toggle, it would just crash Minecraft. This bug is super irritating tbh, especially since it seems to rear it's ugly head out of nowhere for no reason

btw, the crash message i get is this: 

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "pro.mikey.fabric.xray.storage.BlockStore.get()" is null

**Comment by TaylorFarny** [comment]
Did you ever find a solution to this error?

**Comment by chunknugget** [comment]
also wondering if any solution has been found

**Comment by TaylorFarny** [comment]
I got it to work by creating a forge profile instead of fabric for 1.20.3. As of now fabric still breaks for me

**Comment by MichaelHillcox** [comment]
Please attach a full crashlog. I can't do anything without one

**Comment by pairaducks** [comment]
I ran into just today. I looked at config\advanced-xray-fabric\ and found "settings.json and blocks.json. 
Viewing them with Notepad++, blocks.json was empty. Settings.json contained about 20 nuls, repeated in a row. 

Deleting these 2 files, then restarting Minecraft resolved the issue. Upon first use, the files were recreated. 
My block settings were maintained as well. Essentially, the mod behaved normally, again. 

I had the exact same error as OP. The prior exit was a clean exit with no crashes or errors. 

Curseforge launcher
Minecraft version 1.21.1
Fabric version 0.16.5
Advanced Xray version 21.0.0

**Comment by MichaelHillcox** [comment]
Yeah, this seems to be really specific to file corruption. I'm not really sure how to reproduce this but the solution is to just remove the files and restart the game. Thanks for the crashlog :D

**Comment by poypoy007** [comment]
removing the config file doesnt work for me unfortunately. I press the keybing to open the xray/gui and it says saving world the ncrashes.

heres the crash log
[crash-2025-02-07_18.49.44-client.txt](https://github.com/user-attachments/files/18708999/crash-2025-02-07_18.49.44-client.txt)
