### ISSUE TITLE
Minecraft crash when I use Advanced Xray with Overloaded Armor Bar.

### ISSUE THREAD

**Issue by GameGuard4486685095** [AdvancedXRay/XRay-Fabric#86]
**Describe the bug**
Minecraft can not launch when I use Overloaded Armor Bar with this mod.

**To Reproduce**
1. Download Minecraft 1.20.1 with Fabric 0.15.7,fabric-api 0.92.0.
2. Put Advanced Xray and Overloaded Armor Bar in the mod folder.
3. Launch Minecraft ,but failed.

**Expected behavior**
Dont fail to launch

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: 1.20.1
 - XRay Mod Version: fabric-1.20.1-1.6.0-build.17

**Additional context**
this is crash report
[crash-2024-03-24_18.50.46-client.txt](https://github.com/AdvancedXRay/XRay-Fabric/files/14735459/crash-2024-03-24_18.50.46-client.txt)

**Comment by MichaelHillcox** [comment]
I'm not sure why my mod was blamed but this isn't my mods issue.
