### ISSUE TITLE
Game "Crash"

### ISSUE THREAD

**Issue by JayRPlayz** [AdvancedXRay/XRay-Fabric#88]
**Describe the bug**
when i start my game, my game closes with no crash report

**Expected behavior**
Start my Game

**Minecraft Enviorment**
 - Minecraft Version: 1.20.4
 - XRay Mod Version: 2.3.2
 - Fabric Loader Version: 1.15.10

**Comment by MichaelHillcox** [comment]
Please attach your debug.log

**Comment by JayRPlayz** [comment]
there is no "debug.log" do you mean "latest.log"?

**Comment by MichaelHillcox** [comment]
Sure
