### ISSUE TITLE
Doesn't really work

### ISSUE THREAD

**Issue by 34rdsseee** [AdvancedXRay/XRay-Fabric#92]
I tried to use the mod, tried all distances and didn't work. X-ray didn't activate.

Steps
1. Press G
2. Select the blocks you want
3. Click backslash and it won't work.

i thought it would start the X-ray. tried removing my mods from mods folder except for fabric API, and still doesn't work.

**Minecraft Enviorment**
 - Minecraft Version: 1.20.6
 - XRay Mod Version: 86.0.0
 - Mods: Fabric API, X-ray and Zume
 - Fabric version

**Comment by MichaelHillcox** [comment]
Do you have another mods installed?

**Comment by 34rdsseee** [comment]
I also use "zume" but i removed it from the mods folder to see if x ray worked and it didn't.

**Comment by MichaelHillcox** [comment]
Are you running the graphics in fabulous mode?

**Comment by 34rdsseee** [comment]
Yes, i do

**Comment by MichaelHillcox** [comment]
Try not using that

**Comment by 34rdsseee** [comment]
It still doesn't work

**Comment by 34rdsseee** [comment]
What can i do?

A quinta, 16/05/2024, 00:12, Michael Hillcox ***@***.***>
escreveu:

**Comment by MichaelHillcox** [comment]
Can you send over your config file?

**Comment by 34rdsseee** [comment]
How do i send it? Also can i send it through Discord?
