### ISSUE TITLE
i cant find it ungame under resurcepacks

### ISSUE THREAD

**Issue by Timmit22** [AdvancedXRay/XRay-Fabric#95]
**Describe the bug**

**To Reproduce**
1. step one

**Expected behavior**

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.12.2]
 - XRay Mod Version: [eg: 1.5.0]
 - Mod Pack & Version if applicable
 - Forge Version if applicable

**Additional context**

**Comment by MichaelHillcox** [comment]
It's not a resource pack
