### ISSUE TITLE
Game crashing with Xray mod activated [found solution]

### ISSUE THREAD

**Issue by Lower32t** [AdvancedXRay/XRay-Fabric#99]
Well, everything was very good, but one day later of play with the mod, it suddenly crash when i use it, i enter to a world, server or anything, and it just crashes, with a code error -1, with this line of texts (image over there)

Just enter in the server, world, or anything, in the menu everything work fine, but yeah, it crashes later of join

Well, maybe its some of my configs? but i dont know, i literally did nothing since the last time playing with the mod, still, maybe yeah, i did something with my configs or something and i dont remember clearly

![imagen_2024-07-28_161742891](https://github.com/user-attachments/assets/41401c0a-142e-4886-b95c-cc2927c0700d)

 - Minecraft Version: [eg: 1.21]
 - XRay Mod Version: [eg: 21.0.0]

-------------------------------HOW SOLVE:--------------------------------

okay, i talked with Mikey, the mod creator, and the thing you need to do with this crash is the next steps:

1. You need go to the .minecraft folder
2. the "config" folder
3. and you need to detele the entire folder with the name "advanced-xray-fabric"

that worked good for me, yeah, you need to put your keybinds and stuff again, but it worth, thanks Mikey

**Comment by MichaelHillcox** [comment]
Please attach the full crashlog

**Comment by Lower32t** [comment]
> Please attach the full crashlog

hm, thats all what i have
